dist: xenial
sudo: required
language: node_js
node_js:
  - "9.4.0"

env:
  - NODE_ENV=test
  - BABEL_ENV=test

matrix:
  include:
    - os: linux
      dist: xenial
      before_install:
      - sudo add-apt-repository ppa:ethereum/ethereum -y
      - sudo apt-get update
      - sudo apt-get install build-essential -y
      - sudo apt-get install gcc g++ libssl-dev libudev-dev pkg-config
      - curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - rm -rf node_modules

install:
  - npm install
  - npm install -g ganache-cli truffle@4.0.0-beta.0

script:
  - kill -9 $(lsof -t -i:8545)
  - ganache-cli --gasLimit 9999999999999999 2> /dev/null 1> /dev/null &
  - sleep 5
  - rm -rf build
  - truffle compile
  - truffle migrate --reset --network development
  - truffle test
  - kill -9 $(lsof -t -i:8545)
