sudo: required
language: node_js
node_js:
  - "9.4.0"
os: linux
dist: precise

before_install:
  - sudo add-apt-repository ppa:ethereum/ethereum -y
  - sudo apt-get update
  - sudo apt-get install build-essential -y
  - sudo apt-get install gcc g++ libssl-dev libudev-dev pkg-config
  - sudo apt-get install -y nodejs

install:
  - npm install -g ganache-cli truffle

script:
  - ganache-cli -p 7545 > /dev/null &
  - sleep 10
  - truffle migrate
  - truffle test

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"